// All world countries with ISO codes, dial codes, and flag emojis.
// Flag emoji is derived from the country's ISO 3166-1 alpha-2 code by
// mapping each letter to a regional indicator symbol.

export type Country = {
  code: string // ISO 3166-1 alpha-2, e.g. "EG"
  name: string // English name
  nameAr: string // Arabic name
  dialCode: string // e.g. "+20"
  flag: string // emoji flag
}

function flag(code: string): string {
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map((c) => 0x1f1e6 - 65 + c.charCodeAt(0)),
  )
}

const rawCountries: Array<[string, string, string, string]> = [
  // [ISO, EN name, AR name, dial code]
  ['EG', 'Egypt', 'مصر', '+20'],
  ['SA', 'Saudi Arabia', 'السعودية', '+966'],
  ['AE', 'United Arab Emirates', 'الإمارات', '+971'],
  ['KW', 'Kuwait', 'الكويت', '+965'],
  ['QA', 'Qatar', 'قطر', '+974'],
  ['BH', 'Bahrain', 'البحرين', '+973'],
  ['OM', 'Oman', 'عُمان', '+968'],
  ['JO', 'Jordan', 'الأردن', '+962'],
  ['PS', 'Palestine', 'فلسطين', '+970'],
  ['LB', 'Lebanon', 'لبنان', '+961'],
  ['SY', 'Syria', 'سوريا', '+963'],
  ['IQ', 'Iraq', 'العراق', '+964'],
  ['YE', 'Yemen', 'اليمن', '+967'],
  ['SD', 'Sudan', 'السودان', '+249'],
  ['LY', 'Libya', 'ليبيا', '+218'],
  ['TN', 'Tunisia', 'تونس', '+216'],
  ['DZ', 'Algeria', 'الجزائر', '+213'],
  ['MA', 'Morocco', 'المغرب', '+212'],
  ['MR', 'Mauritania', 'موريتانيا', '+222'],
  ['SO', 'Somalia', 'الصومال', '+252'],
  ['DJ', 'Djibouti', 'جيبوتي', '+253'],
  ['KM', 'Comoros', 'جزر القمر', '+269'],
  ['US', 'United States', 'الولايات المتحدة', '+1'],
  ['CA', 'Canada', 'كندا', '+1'],
  ['GB', 'United Kingdom', 'المملكة المتحدة', '+44'],
  ['FR', 'France', 'فرنسا', '+33'],
  ['DE', 'Germany', 'ألمانيا', '+49'],
  ['IT', 'Italy', 'إيطاليا', '+39'],
  ['ES', 'Spain', 'إسبانيا', '+34'],
  ['PT', 'Portugal', 'البرتغال', '+351'],
  ['NL', 'Netherlands', 'هولندا', '+31'],
  ['BE', 'Belgium', 'بلجيكا', '+32'],
  ['CH', 'Switzerland', 'سويسرا', '+41'],
  ['AT', 'Austria', 'النمسا', '+43'],
  ['SE', 'Sweden', 'السويد', '+46'],
  ['NO', 'Norway', 'النرويج', '+47'],
  ['DK', 'Denmark', 'الدانمرك', '+45'],
  ['FI', 'Finland', 'فنلندا', '+358'],
  ['IS', 'Iceland', 'آيسلندا', '+354'],
  ['IE', 'Ireland', 'أيرلندا', '+353'],
  ['PL', 'Poland', 'بولندا', '+48'],
  ['CZ', 'Czech Republic', 'التشيك', '+420'],
  ['SK', 'Slovakia', 'سلوفاكيا', '+421'],
  ['HU', 'Hungary', 'المجر', '+36'],
  ['RO', 'Romania', 'رومانيا', '+40'],
  ['BG', 'Bulgaria', 'بلغاريا', '+359'],
  ['GR', 'Greece', 'اليونان', '+30'],
  ['HR', 'Croatia', 'كرواتيا', '+385'],
  ['RS', 'Serbia', 'صربيا', '+381'],
  ['SI', 'Slovenia', 'سلوفينيا', '+386'],
  ['BA', 'Bosnia and Herzegovina', 'البوسنة والهرسك', '+387'],
  ['MK', 'North Macedonia', 'مقدونيا الشمالية', '+389'],
  ['AL', 'Albania', 'ألبانيا', '+355'],
  ['ME', 'Montenegro', 'الجبل الأسود', '+382'],
  ['RU', 'Russia', 'روسيا', '+7'],
  ['UA', 'Ukraine', 'أوكرانيا', '+380'],
  ['BY', 'Belarus', 'بيلاروس', '+375'],
  ['MD', 'Moldova', 'مولدوفا', '+373'],
  ['LT', 'Lithuania', 'ليتوانيا', '+370'],
  ['LV', 'Latvia', 'لاتفيا', '+371'],
  ['EE', 'Estonia', 'إستونيا', '+372'],
  ['TR', 'Turkey', 'تركيا', '+90'],
  ['CY', 'Cyprus', 'قبرص', '+357'],
  ['MT', 'Malta', 'مالطة', '+356'],
  ['LU', 'Luxembourg', 'لوكسمبورغ', '+352'],
  ['MC', 'Monaco', 'موناكو', '+377'],
  ['AD', 'Andorra', 'أندورا', '+376'],
  ['SM', 'San Marino', 'سان مارينو', '+378'],
  ['VA', 'Vatican City', 'الفاتيكان', '+379'],
  ['CN', 'China', 'الصين', '+86'],
  ['JP', 'Japan', 'اليابان', '+81'],
  ['KR', 'South Korea', 'كوريا الجنوبية', '+82'],
  ['KP', 'North Korea', 'كوريا الشمالية', '+850'],
  ['IN', 'India', 'الهند', '+91'],
  ['PK', 'Pakistan', 'باكستان', '+92'],
  ['BD', 'Bangladesh', 'بنغلاديش', '+880'],
  ['LK', 'Sri Lanka', 'سريلانكا', '+94'],
  ['NP', 'Nepal', 'نيبال', '+977'],
  ['BT', 'Bhutan', 'بوتان', '+975'],
  ['MV', 'Maldives', 'المالديف', '+960'],
  ['TH', 'Thailand', 'تايلاند', '+66'],
  ['MY', 'Malaysia', 'ماليزيا', '+60'],
  ['SG', 'Singapore', 'سنغافورة', '+65'],
  ['ID', 'Indonesia', 'إندونيسيا', '+62'],
  ['PH', 'Philippines', 'الفلبين', '+63'],
  ['VN', 'Vietnam', 'فيتنام', '+84'],
  ['LA', 'Laos', 'لاوس', '+856'],
  ['KH', 'Cambodia', 'كمبوديا', '+855'],
  ['MM', 'Myanmar', 'ميانمار', '+95'],
  ['BN', 'Brunei', 'بروناي', '+673'],
  ['TL', 'Timor-Leste', 'تيمور الشرقية', '+670'],
  ['AF', 'Afghanistan', 'أفغانستان', '+93'],
  ['IR', 'Iran', 'إيران', '+98'],
  ['UZ', 'Uzbekistan', 'أوزبكستان', '+998'],
  ['KZ', 'Kazakhstan', 'كازاخستان', '+7'],
  ['KG', 'Kyrgyzstan', 'قيرغيزستان', '+996'],
  ['TJ', 'Tajikistan', 'طاجيكستان', '+992'],
  ['TM', 'Turkmenistan', 'تركمانستان', '+993'],
  ['MN', 'Mongolia', 'منغوليا', '+976'],
  ['AU', 'Australia', 'أستراليا', '+61'],
  ['NZ', 'New Zealand', 'نيوزيلندا', '+64'],
  ['FJ', 'Fiji', 'فيجي', '+679'],
  ['PG', 'Papua New Guinea', 'بابوا غينيا الجديدة', '+675'],
  ['SB', 'Solomon Islands', 'جزر سليمان', '+677'],
  ['VU', 'Vanuatu', 'فانواتو', '+678'],
  ['WS', 'Samoa', 'ساموا', '+685'],
  ['TO', 'Tonga', 'تونغا', '+676'],
  ['BR', 'Brazil', 'البرازيل', '+55'],
  ['AR', 'Argentina', 'الأرجنتين', '+54'],
  ['CL', 'Chile', 'تشيلي', '+56'],
  ['CO', 'Colombia', 'كولومبيا', '+57'],
  ['PE', 'Peru', 'بيرو', '+51'],
  ['VE', 'Venezuela', 'فنزويلا', '+58'],
  ['BO', 'Bolivia', 'بوليفيا', '+591'],
  ['EC', 'Ecuador', 'الإكوادور', '+593'],
  ['PY', 'Paraguay', 'باراغواي', '+595'],
  ['UY', 'Uruguay', 'الأوروغواي', '+598'],
  ['GY', 'Guyana', 'غيانا', '+592'],
  ['SR', 'Suriname', 'سورينام', '+597'],
  ['MX', 'Mexico', 'المكسيك', '+52'],
  ['GT', 'Guatemala', 'غواتيمالا', '+502'],
  ['HN', 'Honduras', 'هندوراس', '+504'],
  ['SV', 'El Salvador', 'السلفادور', '+503'],
  ['NI', 'Nicaragua', 'نيكاراغوا', '+505'],
  ['CR', 'Costa Rica', 'كوستاريكا', '+506'],
  ['PA', 'Panama', 'بنما', '+507'],
  ['BZ', 'Belize', 'بليز', '+501'],
  ['CU', 'Cuba', 'كوبا', '+53'],
  ['DO', 'Dominican Republic', 'جمهورية الدومينيكان', '+1'],
  ['HT', 'Haiti', 'هايتي', '+509'],
  ['JM', 'Jamaica', 'جامايكا', '+1'],
  ['TT', 'Trinidad and Tobago', 'ترينيداد وتوباغو', '+1'],
  ['BS', 'Bahamas', 'الباهاما', '+1'],
  ['BB', 'Barbados', 'بربادوس', '+1'],
  ['GD', 'Grenada', 'غرينادا', '+1'],
  ['LC', 'Saint Lucia', 'سانت لوسيا', '+1'],
  ['VC', 'Saint Vincent and the Grenadines', 'سانت فينسنت', '+1'],
  ['AG', 'Antigua and Barbuda', 'أنتيغوا وباربودا', '+1'],
  ['DM', 'Dominica', 'دومينيكا', '+1'],
  ['KN', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', '+1'],
  ['ZA', 'South Africa', 'جنوب أفريقيا', '+27'],
  ['NG', 'Nigeria', 'نيجيريا', '+234'],
  ['KE', 'Kenya', 'كينيا', '+254'],
  ['GH', 'Ghana', 'غانا', '+233'],
  ['ET', 'Ethiopia', 'إثيوبيا', '+251'],
  ['TZ', 'Tanzania', 'تنزانيا', '+255'],
  ['UG', 'Uganda', 'أوغندا', '+256'],
  ['CM', 'Cameroon', 'الكاميرون', '+237'],
  ['CI', "Côte d'Ivoire", 'ساحل العاج', '+225'],
  ['SN', 'Senegal', 'السنغال', '+221'],
  ['ZM', 'Zambia', 'زامبيا', '+260'],
  ['ZW', 'Zimbabwe', 'زيمبابوي', '+263'],
  ['RW', 'Rwanda', 'رواندا', '+250'],
  ['BI', 'Burundi', 'بوروندي', '+257'],
  ['MZ', 'Mozambique', 'موزمبيق', '+258'],
  ['AO', 'Angola', 'أنغولا', '+244'],
  ['MZ2', 'Madagascar', 'مدغشقر', '+261'],
  ['MW', 'Malawi', 'مالاوي', '+265'],
  ['ML', 'Mali', 'مالي', '+223'],
  ['BF', 'Burkina Faso', 'بوركينا فاسو', '+226'],
  ['NE', 'Niger', 'النيجر', '+227'],
  ['TG', 'Togo', 'توغو', '+228'],
  ['BJ', 'Benin', 'بنين', '+229'],
  ['SL', 'Sierra Leone', 'سيراليون', '+232'],
  ['LR', 'Liberia', 'ليبيريا', '+231'],
  ['GN', 'Guinea', 'غينيا', '+224'],
  ['GW', 'Guinea-Bissau', 'غينيا بيساو', '+245'],
  ['CV', 'Cape Verde', 'الرأس الأخضر', '+238'],
  ['ST', 'São Tomé and Príncipe', 'ساو تومي وبرينسيبي', '+239'],
  ['GA', 'Gabon', 'الغابون', '+241'],
  ['CG', 'Congo', 'الكونغو', '+242'],
  ['CD', 'DR Congo', 'الكونغو الديمقراطية', '+243'],
  ['CF', 'Central African Republic', 'أفريقيا الوسطى', '+236'],
  ['TD', 'Chad', 'تشاد', '+235'],
  ['EH', 'Western Sahara', 'الصحراء الغربية', '+212'],
  ['LS', 'Lesotho', 'ليسوتو', '+266'],
  ['SZ', 'Eswatini', 'إسواتيني', '+268'],
  ['NA', 'Namibia', 'ناميبيا', '+264'],
  ['BW', 'Botswana', 'بوتسوانا', '+267'],
  ['MU', 'Mauritius', 'موريشيوس', '+230'],
  ['SC', 'Seychelles', 'سيشل', '+248'],
  ['RE', 'Réunion', 'ريونيون', '+262'],
  ['YT', 'Mayotte', 'مايوت', '+262'],
  ['TW', 'Taiwan', 'تايوان', '+886'],
  ['HK', 'Hong Kong', 'هونغ كونغ', '+852'],
  ['MO', 'Macao', 'ماكاو', '+853'],
  ['GE', 'Georgia', 'جورجيا', '+995'],
  ['AM', 'Armenia', 'أرمينيا', '+374'],
  ['AZ', 'Azerbaijan', 'أذربيجان', '+994'],
]

// Deduplicate by code (handle MZ2 → MZ alias)
export const COUNTRIES: Country[] = rawCountries
  .filter(([code]) => !code.endsWith('2'))
  .map(([code, name, nameAr, dialCode]) => ({
    code,
    name,
    nameAr,
    dialCode,
    flag: flag(code),
  }))
  .concat(
    // Add Madagascar which was tagged MZ2 above
    rawCountries
      .filter(([code]) => code === 'MZ2')
      .map(([_code, name, nameAr, dialCode]) => ({
        code: 'MG',
        name,
        nameAr,
        dialCode,
        flag: flag('MG'),
      })),
  )
  .sort((a, b) => a.code.localeCompare(b.code))

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code)
}

export function getCountryByDialCode(dial: string): Country | undefined {
  return COUNTRIES.find((c) => c.dialCode === dial)
}

export const DEFAULT_COUNTRY = getCountryByCode('EG') || COUNTRIES[0]
